/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;




import javax.swing.ImageIcon;
import static presentacion.Inicial.contar;
import static presentacion.Juego1.array;

/**
 *
 * @author Natal
 */
public class Opciones extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form Opciones
     */
    public Opciones() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeguir = new javax.swing.JButton();
        btnCarrito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSeguir.setText("Seguir comprando");
        btnSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 101, -1, -1));

        btnCarrito.setText("Carrito");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 101, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        // TODO add your handling code here:
        
        Carrito car= new Carrito();
        car.setVisible(true);
       
        
        
        ImageIcon phasmo = new ImageIcon(Opciones.class.getResource("phasmo.png"));
        ImageIcon dbd = new ImageIcon(Opciones.class.getResource("dbd.png"));
        ImageIcon idv = new ImageIcon(Opciones.class.getResource("idv.png"));
        ImageIcon out = new ImageIcon(Opciones.class.getResource("out.png"));
       
        
        
        
         
        if (array.get(0) == "100"){
            Carrito.txtnomjueg0.setText("Phasmophobia");
            contar[0]=100;
            Carrito.lbl0.setText("Terror / Cooperativo");
            Carrito.txtPrecio0.setText("$100.00"); 
            Carrito.btnImagen0.setIcon(phasmo);
        }
        else if (array.get(0) == "200"){
            Carrito.txtnomjueg0.setText("Dead by Daylight");
            contar[0]=200;
            Carrito.lbl0.setText("Terror / 4vs1 / Supervivencia");
            Carrito.txtPrecio0.setText("$200.00");
            Carrito.btnImagen0.setIcon(dbd);
        }
        else if (array.get(0) == "300"){
            Carrito.txtnomjueg0.setText("Identity V");
            contar[0]=300;
            Carrito.lbl0.setText("Terror / 4vs1 / Supervivencia / Rank");
            Carrito.txtPrecio0.setText("$300.00");
            Carrito.btnImagen0.setIcon(idv);
        }
        else if (array.get(0) == "400"){
            Carrito.txtnomjueg0.setText("Outlast");
            contar[0]=400;
            Carrito.lbl0.setText("Terror psicológico / Un jugador / Historia");
            Carrito.txtPrecio0.setText("$400.00");
            Carrito.btnImagen0.setIcon(out);
        }
        
        
        if (array.get(1) == "200"){
            Carrito.txtnomjueg1.setText("Dead by Daylight");
            contar[1]=200;
            Carrito.lbl1.setText("Terror / 4vs1 / Supervivencia");
            Carrito.txtPrecio1.setText("$200.00");
            Carrito.btnImagen1.setIcon(dbd);
        }
        else if (array.get(1) == "100"){
            Carrito.txtnomjueg1.setText("Phasmophobia");
            contar[1]=100;
            Carrito.lbl1.setText("Terror / Cooperativo ");
            Carrito.txtPrecio1.setText("$100.00");
            Carrito.btnImagen1.setIcon(phasmo);
        }
        else if (array.get(1) == "300"){
            Carrito.txtnomjueg1.setText("Identity V");
            contar[1]=300;
            Carrito.lbl1.setText("Terror / 4vs1 / Supervivencia / Rank");
            Carrito.txtPrecio1.setText("$300.00");
            Carrito.btnImagen1.setIcon(idv);
        }
        else if (array.get(1) == "400"){
            Carrito.txtnomjueg1.setText("Outlast");
            contar[1]=400;
            Carrito.lbl1.setText("Terror psicológico / Un jugador / Historia");
            Carrito.txtPrecio1.setText("$400.00");
            Carrito.btnImagen1.setIcon(out);
        }
        
        
        if (array.get(2) == "300"){
            Carrito.txtnomjueg2.setText("Identity V");
            contar[2]=300;
            Carrito.lbl2.setText("Terror / 4vs1 / Supervivencia / Rank");
            Carrito.txtPrecio2.setText("$300.00");
            Carrito.btnImagen2.setIcon(idv);
        }
        else if (array.get(2) == "100"){
            Carrito.txtnomjueg2.setText("Phasmophobia");
            contar[2]=100;
            Carrito.lbl2.setText("Terror / Cooperativo ");
            Carrito.txtPrecio2.setText("$100.00");
            Carrito.btnImagen2.setIcon(phasmo);
        }
        else if (array.get(2) == "200"){
            Carrito.txtnomjueg2.setText("Dead by Daylight");
            contar[2]=200;
            Carrito.lbl2.setText("Terror / 4vs1 / Supervivencia");
            Carrito.txtPrecio2.setText("$200.00");
            Carrito.btnImagen2.setIcon(dbd);
        }
        else if (array.get(2) == "400"){
            Carrito.txtnomjueg2.setText("Outlast");
            contar[2]=400;
            Carrito.lbl2.setText("Terror psicológico / Un jugador / Historia");
            Carrito.txtPrecio2.setText("$400.00");
            Carrito.btnImagen2.setIcon(out);
        }
        
        
        if (array.get(3) == "400"){
            Carrito.txtnomjueg3.setText("Outlast");
            contar[3]=400;
            Carrito.lbl3.setText("Terror psicológico / Un jugador / Historia");
            Carrito.txtPrecio3.setText("$400.00");
            Carrito.btnImagen3.setIcon(out);
        }
        else if (array.get(3) == "100"){
            Carrito.txtnomjueg3.setText("Phasmophobia");
            contar[3]=100;
            Carrito.lbl3.setText("Terror / Cooperativo ");
            Carrito.txtPrecio3.setText("$100.00");
            Carrito.btnImagen3.setIcon(phasmo);
        }
        else if (array.get(3) == "200"){
            Carrito.txtnomjueg3.setText("Dead by Daylight");
            contar[3]=200;
            Carrito.lbl3.setText("Terror / 4vs1 / Supervivencia");
            Carrito.txtPrecio3.setText("$200.00");
            Carrito.btnImagen3.setIcon(dbd);
        }
        else if (array.get(3) == "300"){
            Carrito.txtnomjueg3.setText("Identity V");
            contar[3]=300;
            Carrito.lbl3.setText("Terror / 4vs1 / Supervivencia / Rank");
            Carrito.txtPrecio3.setText("$300.00");
            Carrito.btnImagen3.setIcon(idv);
            
        }
       
        this.dispose();
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void btnSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguirActionPerformed
        // TODO add your handling code here:
        Inicial frmInicial = new Inicial();
        frmInicial.setVisible(true);
    }//GEN-LAST:event_btnSeguirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnSeguir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
